import { data } from "react-router-dom";

const Données=[
    {
        id: 1,
        name: "hotel le truc",
        image: "/images/1.jpg",
        ville: "alger",
            details:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum gravida nisi, consectetur bibendum ex dapibus eu. Morbi fringilla, eros ut feugiat consequat, odio odio euismod elit, ut blandit odio leo a tortor. Pellentesque vitae enim eget nunc luctus dapibus a eget turpis. Ut placerat, turpis id vehicula aliquam, justo eros commodo purus, a placerat nunc metus at erat. In nunc urna, interdum vitae bibendum ut, fermentum sit amet enim. Suspendisse eget tincidunt dui. Vestibulum et bibendum tortor. Aenean congue lectus suscipit, viverra metus at, convallis ligula. Aliquam ut risus at massa dignissim ultrices. Cras tempus nisi et iaculis vestibulum. Sed convallis diam eu eros molestie, ut placerat purus ultricies. Nam viverra, nisi auctor pulvinar lacinia, enim dui consequat elit, nec facilisis dui sapien sed erat. Nam ac felis quis purus dignissim sagittis id eu turpis. Vivamus ac ex sed est volutpat laoreet. Proin id sagittis est, quis porttitor mi. Donec est leo, molestie vitae semper vel, dapibus commodo sem. Sed ultricies scelerisque est quis viverra. Duis ut lorem vitae magna imperdiet rhoncus. Etiam hendrerit ante ut semper dignissim. Cras sagittis purus vel purus facilisis, id sodales velit tincidunt. In hac habitasse platea dictumst. Mauris pharetra viverra odio, sit amet hendrerit mauris. Sed convallis elementum enim, id sollicitudin libero faucibus vel. Integer arcu leo, dignissim ut rhoncus quis, vulputate a metus. Nulla enim ipsum, egestas nec turpis et, feugiat dictum dolor. Mauris in eros porttitor, eleifend ipsum ac, lacinia lorem. Quisque sem odio, ornare eu ante sit amet, volutpat facilisis erat. Pellentesque vestibulum consequat egestas. Suspendisse non dapibus neque. Suspendisse id tempor ligula. Proin aliquam elit eu sapien tincidunt, at varius est pulvinar.Nunc faucibus urna tortor, vel pellentesque purus tincidunt in. Ut in risus eget odio fermentum accumsan. Donec odio nisl, mollis malesuada dolor tristique, aliquam consectetur ex. Pellentesque tempus placerat nisi, a faucibus neque faucibus ac. Curabitur iaculis vestibulum quam, pulvinar mattis nulla eleifend a. Nunc sagittis mauris at orci dignissim volutpat. Praesent aliquet mattis suscipit.",

},
{
    id: 2,
    name: "hotel le machain",
    image: "/images/2.jpg",
    ville: "alger",
    details:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum gravida nisi, consectetur bibendum ex dapibus eu. Morbi fringilla, eros ut feugiat consequat, odio odio euismod elit, ut blandit odio leo a tortor. Pellentesque vitae enim eget nunc luctus dapibus a eget turpis. Ut placerat, turpis id vehicula aliquam, justo eros commodo purus, a placerat nunc metus at erat. In nunc urna, interdum vitae bibendum ut, fermentum sit amet enim. Suspendisse eget tincidunt dui. Vestibulum et bibendum tortor. Aenean congue lectus suscipit, viverra metus at, convallis ligula. Aliquam ut risus at massa dignissim ultrices. Cras tempus nisi et iaculis vestibulum. Sed convallis diam eu eros molestie, ut placerat purus ultricies. Nam viverra, nisi auctor pulvinar lacinia, enim dui consequat elit, nec facilisis dui sapien sed erat. Nam ac felis quis purus dignissim sagittis id eu turpis. Vivamus ac ex sed est volutpat laoreet. Proin id sagittis est, quis porttitor mi. Donec est leo, molestie vitae semper vel, dapibus commodo sem. Sed ultricies scelerisque est quis viverra. Duis ut lorem vitae magna imperdiet rhoncus. Etiam hendrerit ante ut semper dignissim. Cras sagittis purus vel purus facilisis, id sodales velit tincidunt. In hac habitasse platea dictumst. Mauris pharetra viverra odio, sit amet hendrerit mauris. Sed convallis elementum enim, id sollicitudin libero faucibus vel. Integer arcu leo, dignissim ut rhoncus quis, vulputate a metus. Nulla enim ipsum, egestas nec turpis et, feugiat dictum dolor. Mauris in eros porttitor, eleifend ipsum ac, lacinia lorem. Quisque sem odio, ornare eu ante sit amet, volutpat facilisis erat. Pellentesque vestibulum consequat egestas. Suspendisse non dapibus neque. Suspendisse id tempor ligula. Proin aliquam elit eu sapien tincidunt, at varius est pulvinar.Nunc faucibus urna tortor, vel pellentesque purus tincidunt in. Ut in risus eget odio fermentum accumsan. Donec odio nisl, mollis malesuada dolor tristique, aliquam consectetur ex. Pellentesque tempus placerat nisi, a faucibus neque faucibus ac. Curabitur iaculis vestibulum quam, pulvinar mattis nulla eleifend a. Nunc sagittis mauris at orci dignissim volutpat. Praesent aliquet mattis suscipit.",
},
{ id: 3,
    name: "hotel le bidule",
    image: "/images/3.jpg",
    ville: "oran",
        details:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum gravida nisi, consectetur bibendum ex dapibus eu. Morbi fringilla, eros ut feugiat consequat, odio odio euismod elit, ut blandit odio leo a tortor. Pellentesque vitae enim eget nunc luctus dapibus a eget turpis. Ut placerat, turpis id vehicula aliquam, justo eros commodo purus, a placerat nunc metus at erat. In nunc urna, interdum vitae bibendum ut, fermentum sit amet enim. Suspendisse eget tincidunt dui. Vestibulum et bibendum tortor. Aenean congue lectus suscipit, viverra metus at, convallis ligula. Aliquam ut risus at massa dignissim ultrices. Cras tempus nisi et iaculis vestibulum. Sed convallis diam eu eros molestie, ut placerat purus ultricies. Nam viverra, nisi auctor pulvinar lacinia, enim dui consequat elit, nec facilisis dui sapien sed erat. Nam ac felis quis purus dignissim sagittis id eu turpis. Vivamus ac ex sed est volutpat laoreet. Proin id sagittis est, quis porttitor mi. Donec est leo, molestie vitae semper vel, dapibus commodo sem. Sed ultricies scelerisque est quis viverra. Duis ut lorem vitae magna imperdiet rhoncus. Etiam hendrerit ante ut semper dignissim. Cras sagittis purus vel purus facilisis, id sodales velit tincidunt. In hac habitasse platea dictumst. Mauris pharetra viverra odio, sit amet hendrerit mauris. Sed convallis elementum enim, id sollicitudin libero faucibus vel. Integer arcu leo, dignissim ut rhoncus quis, vulputate a metus. Nulla enim ipsum, egestas nec turpis et, feugiat dictum dolor. Mauris in eros porttitor, eleifend ipsum ac, lacinia lorem. Quisque sem odio, ornare eu ante sit amet, volutpat facilisis erat. Pellentesque vestibulum consequat egestas. Suspendisse non dapibus neque. Suspendisse id tempor ligula. Proin aliquam elit eu sapien tincidunt, at varius est pulvinar.Nunc faucibus urna tortor, vel pellentesque purus tincidunt in. Ut in risus eget odio fermentum accumsan. Donec odio nisl, mollis malesuada dolor tristique, aliquam consectetur ex. Pellentesque tempus placerat nisi, a faucibus neque faucibus ac. Curabitur iaculis vestibulum quam, pulvinar mattis nulla eleifend a. Nunc sagittis mauris at orci dignissim volutpat. Praesent aliquet mattis suscipit.",


},
{
    id: 4,
    name: "hotel le quelque chose",
    image: "/images/4.jpg",
    ville: "oran",
        details:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum gravida nisi, consectetur bibendum ex dapibus eu. Morbi fringilla, eros ut feugiat consequat, odio odio euismod elit, ut blandit odio leo a tortor. Pellentesque vitae enim eget nunc luctus dapibus a eget turpis. Ut placerat, turpis id vehicula aliquam, justo eros commodo purus, a placerat nunc metus at erat. In nunc urna, interdum vitae bibendum ut, fermentum sit amet enim. Suspendisse eget tincidunt dui. Vestibulum et bibendum tortor. Aenean congue lectus suscipit, viverra metus at, convallis ligula. Aliquam ut risus at massa dignissim ultrices. Cras tempus nisi et iaculis vestibulum. Sed convallis diam eu eros molestie, ut placerat purus ultricies. Nam viverra, nisi auctor pulvinar lacinia, enim dui consequat elit, nec facilisis dui sapien sed erat. Nam ac felis quis purus dignissim sagittis id eu turpis. Vivamus ac ex sed est volutpat laoreet. Proin id sagittis est, quis porttitor mi. Donec est leo, molestie vitae semper vel, dapibus commodo sem. Sed ultricies scelerisque est quis viverra. Duis ut lorem vitae magna imperdiet rhoncus. Etiam hendrerit ante ut semper dignissim. Cras sagittis purus vel purus facilisis, id sodales velit tincidunt. In hac habitasse platea dictumst. Mauris pharetra viverra odio, sit amet hendrerit mauris. Sed convallis elementum enim, id sollicitudin libero faucibus vel. Integer arcu leo, dignissim ut rhoncus quis, vulputate a metus. Nulla enim ipsum, egestas nec turpis et, feugiat dictum dolor. Mauris in eros porttitor, eleifend ipsum ac, lacinia lorem. Quisque sem odio, ornare eu ante sit amet, volutpat facilisis erat. Pellentesque vestibulum consequat egestas. Suspendisse non dapibus neque. Suspendisse id tempor ligula. Proin aliquam elit eu sapien tincidunt, at varius est pulvinar.Nunc faucibus urna tortor, vel pellentesque purus tincidunt in. Ut in risus eget odio fermentum accumsan. Donec odio nisl, mollis malesuada dolor tristique, aliquam consectetur ex. Pellentesque tempus placerat nisi, a faucibus neque faucibus ac. Curabitur iaculis vestibulum quam, pulvinar mattis nulla eleifend a. Nunc sagittis mauris at orci dignissim volutpat. Praesent aliquet mattis suscipit.",

},
];

export default Données